deploy:
  name: Continuous-Deployment
  runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Debug - Show available Docker images
      run: docker images

    - name: Pull latest image
      run: |
        docker pull ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest

    - name: Stop and remove old container
      run: |
        if [ "$(docker ps -q -f name=myapp)" ]; then
          echo "Stopping old container..."
          docker stop myapp || true
          docker rm myapp || true
        else
          echo "No old container found."
        fi

    - name: Run Docker Image to serve users
      run: |
        echo "Starting new container..."
        docker run -d -p 8000:8000 --name myapp \
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}:latest

    - name: Debug - List running containers
      run: docker ps -a
